/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MooKorea (https://sketchfab.com/MooKorea)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lucille-vgdc-940ca0a626404fcd966a309c03ff2ad9
Title: Lucille | VGDC
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model-with-animations.glb')
  const { actions } = useAnimations(animations, group);
  console.log(actions)
  useEffect(() => {/* highlight-line */
    actions['Walk_g'].play(); /* highlight-line */
  }); /* highlight-line */

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="36f65d3723a448deacbd5d73cb9015bdfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Hair" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Lucille_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group
                  name="Eye_Left"
                  position={[2.905, 142.878, 1.891]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={94.901}
                />
                <group
                  name="Eye_Left001"
                  position={[-2.785, 142.878, 1.891]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={94.901}
                />
                <group
                  name="Eyelashes"
                  position={[0, 150.388, -3.699]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group name="Retopo_Skirt016" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group
                  name="Plane"
                  position={[0, 137.424, 4.098]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group name="Lucille_Body001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Retopo_Skirt001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="rig_deform" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_14">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_17"
                      geometry={nodes.Object_17.geometry}
                      material={materials.Hair}
                      skeleton={nodes.Object_17.skeleton}
                    />
                    <skinnedMesh
                      name="Object_18"
                      geometry={nodes.Object_18.geometry}
                      material={materials.Hair_Flyaway}
                      skeleton={nodes.Object_18.skeleton}
                    />
                    <skinnedMesh
                      name="Object_19"
                      geometry={nodes.Object_19.geometry}
                      material={materials.Clothes_Nonfabric}
                      skeleton={nodes.Object_19.skeleton}
                    />
                    <skinnedMesh
                      name="Object_21"
                      geometry={nodes.Object_21.geometry}
                      material={materials.Lucille_Skin_Head}
                      skeleton={nodes.Object_21.skeleton}
                    />
                    <skinnedMesh
                      name="Object_22"
                      geometry={nodes.Object_22.geometry}
                      material={materials.Lucille_Body}
                      skeleton={nodes.Object_22.skeleton}
                    />
                    <skinnedMesh
                      name="Object_23"
                      geometry={nodes.Object_23.geometry}
                      material={materials.Stocking}
                      skeleton={nodes.Object_23.skeleton}
                    />
                    <skinnedMesh
                      name="Object_24"
                      geometry={nodes.Object_24.geometry}
                      material={materials.Clothes_Nonfabric}
                      skeleton={nodes.Object_24.skeleton}
                    />
                    <skinnedMesh
                      name="Object_26"
                      geometry={nodes.Object_26.geometry}
                      material={materials.material}
                      skeleton={nodes.Object_26.skeleton}
                    />
                    <skinnedMesh
                      name="Object_28"
                      geometry={nodes.Object_28.geometry}
                      material={materials.material}
                      skeleton={nodes.Object_28.skeleton}
                    />
                    <skinnedMesh
                      name="Object_30"
                      geometry={nodes.Object_30.geometry}
                      material={materials.Eyelashes}
                      skeleton={nodes.Object_30.skeleton}
                    />
                    <skinnedMesh
                      name="Object_32"
                      geometry={nodes.Object_32.geometry}
                      material={materials.Clothes_Fabric}
                      skeleton={nodes.Object_32.skeleton}
                    />
                    <skinnedMesh
                      name="Object_33"
                      geometry={nodes.Object_33.geometry}
                      material={materials.Clothes_Nonfabric}
                      skeleton={nodes.Object_33.skeleton}
                    />
                    <skinnedMesh
                      name="Object_35"
                      geometry={nodes.Object_35.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_35.skeleton}
                    />
                    <skinnedMesh
                      name="Object_37"
                      geometry={nodes.Object_37.geometry}
                      material={materials.Lucille_Skin_Head}
                      skeleton={nodes.Object_37.skeleton}
                    />
                    <skinnedMesh
                      name="Object_39"
                      geometry={nodes.Object_39.geometry}
                      material={materials.Clothes_Fabric}
                      skeleton={nodes.Object_39.skeleton}
                    />
                    <group name="Object_16" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_20" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group
                      name="Object_25"
                      position={[2.905, 142.878, 1.891]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={94.901}
                    />
                    <group
                      name="Object_27"
                      position={[-2.785, 142.878, 1.891]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={94.901}
                    />
                    <group
                      name="Object_29"
                      position={[0, 150.388, -3.699]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group name="Object_31" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group
                      name="Object_34"
                      position={[0, 137.424, 4.098]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group name="Object_36" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_38" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model-with-animations.glb')


